### ISSUE TITLE
国服还更新吗

### ISSUE THREAD

**Issue by BeginnerSlob** [AinaSnow/FFXIV-database#9]
今天6.51放包了，点开才发现国服的分支很久没更新了

**Comment by AinaSnow** [comment]
最近事比较多 晚上跟进一下

________________________________
From: Slob ***@***.***>
Sent: Monday, April 8, 2024 5:49:53 PM
To: AinaSnow/FFXIV-Datamining ***@***.***>
Cc: Subscribed ***@***.***>
Subject: [AinaSnow/FFXIV-Datamining] 国服还更新吗 (Issue #9)


今天6.51放包了，点开才发现国服的分支很久没更新了

―

**Comment by AinaSnow** [comment]
已更
